export interface IStyle {
   width?: string;
   height?: string;
   display?: string;
   backgroundColor?: string;
   backdropFilter?: string;
   color?: string;
   position?: string;
   top?: string;
   left?: string;
   overflow?: string;
   a?: string;
   span?: string;
   h1?: string;
   div?: string;
   gap?: string;
   zIndex?: string;
   alignItems: string;
   justifyContent: string;
   flexDirection: string;
   padding?: string;
   fontSize?: string;
   fontWeight?: string;
   cursor?: string;
   fontFamily?: string;
   background?: string;
   backgroundRepeat?: string;
   backgroundSize?: string;
}